[package]
name = "cnctd_smart_home"
version = "0.1.0"
edition = "2021"
authors = ["Connected Dot Inc.", "Kyle Ebner <kyle@cnctd.world>"]
description = "A collection of Smart Home APIs"
repository = "https://github.com/Connected-Dot/cnctd_smart_home"
license = "MIT"
keywords = ["module"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
